"""add carried_forward flag

Revision ID: 166877a5de18
Revises: 282339c16199
Create Date: 2025-06-11 16:53:02.547356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166877a5de18'
down_revision = '282339c16199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('carried_forward', sa.Boolean(),
                      nullable=False, server_default=sa.text('0'))
        )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('carried_forward')

    # ### end Alembic commands ###
