"""add status to expense

Revision ID: 282339c16199
Revises: caf88f75884a
Create Date: 2025-06-05 17:03:47.029289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282339c16199'
down_revision = 'caf88f75884a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'canceled'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
