"""add expense_receipt table

Revision ID: 398aba205e65
Revises: 166877a5de18
Create Date: 2025-06-12 17:14:30.964708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '398aba205e65'
down_revision = '166877a5de18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expense.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense_receipt')
    # ### end Alembic commands ###
