"""add final_checked flag

Revision ID: c82a153c03d7
Revises: 398aba205e65
Create Date: 2025-06-12 19:39:15.846186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c82a153c03d7'
down_revision = '398aba205e65'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('expense') as batch_op:
        batch_op.add_column(
            sa.Column(
                'final_checked',
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("0")
            )
        )

    # ### commands auto generated by Alembic - please adjust! ###
    

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('expense') as batch_op:
        batch_op.drop_column('final_checked')

    # ### commands auto generated by Alembic - please adjust! ###
    

    # ### end Alembic commands ###
